### ISSUE TITLE
users_by_followers.py doesnt work

### ISSUE THREAD

**Issue by Nurlan199206** [instagrambot/instapro#6]
when im running script, im getting these errors, whats wrong?
```
python users_by_followers.py
USERS AVAILABLE: 1
unique users: 100it [07:48,  4.39s/it]Traceback (most recent call last):
  File "users_by_followers.py", line 24, in <module>
    scraper.save_users_from_user(get, iterator, path % username, batchsleep=10)
  File "/home/nurlan/instapro/examples/scrapers/scraper.py", line 101, in save_users_from_user
    dump_data(users, output_filename)
  File "/home/nurlan/instapro/examples/scrapers/scraper.py", line 22, in dump_data
    header=(mode == "w"), index=False)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 1403, in to_csv
    formatter.save()
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/formats/format.py", line 1592, in save
    self._save()
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/formats/format.py", line 1693, in _save
    self._save_chunk(start_i, end_i)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/formats/format.py", line 1719, in _save_chunk
    lib.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)
  File "pandas/_libs/lib.pyx", line 1115, in pandas._libs.lib.write_csv_rows (pandas/_libs/lib.c:20130)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
```

**Comment by ohld** [comment]
try to use python3

**Comment by harisprananda** [comment]
Can you explain how I can start this bot that running on the "windows", basically I just confused to set my username and password for login. Your aid to explain very useful for me.. Thanks

**Comment by ohld** [comment]
@harisprananda This bot is for developers only. Go to example folder and look at the code. If you are not a developer, go to instabot repository.
